sonar.organization=aboulmali
sonar.projectKey=afi-backend
sonar.projectName=afi-backend
sonar.sourceEncoding=UTF-8
sonar.sources=app
sonar.tests=tests
sonar.exclusions=alembic/**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
