sonar.projectKey=afi-backend
sonar.projectName=afi-backend
sonar.organization=aboulmali
# main = branche long-lived (analyse SHORT sinon -> gate indisponible)
sonar.branch.name=main
sonar.sourceEncoding=UTF-8
sonar.sources=app
sonar.tests=tests
sonar.exclusions=alembic/**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
