# Configuration SonarQube / SonarCloud
sonar.projectKey=afi-backend
sonar.projectName=AFI Backend
sonar.organization=aboulmali

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12

sonar.exclusions=**/tests/**,**/__pycache__/**,**/venv/**
sonar.test.exclusions=**/tests/**
sonar.sourceEncoding=UTF-8