{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: afi-api
  namespace: {{ .Values.namespace }}
  labels:
    app: afi-api
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: afi-api
                port:
                  number: {{ .Values.service.port }}
{{- end }}
