apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: afi-prod
  labels:
    app: afi-redis
spec:
  selector:
    app: afi-redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: afi-prod
  labels:
    app: afi-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: afi-redis
  template:
    metadata:
      labels:
        app: afi-redis
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          args: ["--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            readOnlyRootFilesystem: true
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi