apiVersion: v1
kind: ConfigMap
metadata:
  name: afi-config
  namespace: afi
data:
  REDIS_URL: "redis://afi-redis:6379"
  APP_NAME: "AFI - Assistant Financier Intelligent"
  DEBUG: "False"
  AWS_REGION: "eu-west-3"
  UPLOADS_BUCKET: "afi-uploads-481665100214"