apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: afi-api
  namespace: afi
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: api.afi.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: afi-api
                port:
                  number: 80